### PR TITLE
Fix button layout, and H2 color

### LINKED ISSUE #189: Headings are different colour when they contain span and strong elements
https://ugnext.netlify.app/ovc/dvm/mentorship-and-opportunities vs https://www.uoguelph.ca/ovc/dvm/mentorship-and-opportunities/

Headings (H2) are different colour when they contain inner elements

Image

First noticed in #174

### PR DESCRIPTION
**Pull request by abanuog**
# Summary of changes
- H2 color back to Red (as previously)
- Buttons are now in the same row
- Partly fixes two issues (#174 , #139)
- Fixes #189

## Frontend
- Remove span and strong tags around h2, using a function
- Updated layout for buttons

- [x] My changes are accessible (at minimum WCAG 2.0 Level AA)
- [x] My changes are responsive and appear as expected on mobile and desktop views.
- [x] My changes have been reviewed to ensure they do not break an existing analytics trigger
- [n/a] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my changes will affect users.

## Backend
n/a

# Test Plan

- Go to https://deploy-preview-184--ugnext.netlify.app/
- Check https://deploy-preview-184--ugnext.netlify.app/ovc/dvm/mentorship-and-opportunities and see if the headings are red.
- Check https://deploy-preview-184--ugnext.netlify.app/housing/communities/lennox-and-addington-hall to see if the buttons under "Residence is where..." are on the same line

### CODE REVIEW

**Review by mmafe — CHANGES_REQUESTED** [review]
Seeing one odd issue with the button headings and the size of the button text (see comments)

File: components/client/widgets/button-section.js [hunk 1]
```diff
@@ -97,9 +97,12 @@ export const ButtonWidget = ({ data, column }) => {
   return (
     <>
       {heading && (
+        <>
```
Comment (mmafe) [inline components/client/widgets/button-section.js]: Hoping we can do this without having an empty div with 0 height.

Maybe:
```
      {heading && (
        <div className="basis-full">
          <Typography id={`button-heading-${data.uuid}`} type="h3" as="h2" className={classes.heading()}>
            <HtmlParser html={heading} />
          </Typography>
        </div>
      )}
```

**Review by mmafe — CHANGES_REQUESTED** [review]
Can we update code so it doesn't use an empty div with 0 height?

**Review by RazaMM — APPROVED** [review]

**Review by mmafe — APPROVED** [review]
